services:
  game-zone:
    container_name: '${COMPOSE_PROJECT_NAME}'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app" # Bind mount the current directory to the '/app' directory inside the container.
      - "/app/node_modules" # Create an anonymous volume for node_modules to persist them independent of the container's lifecycle.

    command: "tail -f /dev/null" # Executes 'tail -f /dev/null' to keep the container running without exiting.
    environment:
      CHOKIDAR_USEPOLLING: "true" # Enable polling for file changes
      NODE_ENV: development
